// Generated by dts-bundle-generator v9.5.1

declare global {
	/**
	 * Native Java Class Object (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html java.lang.Class})
	 */
	type JavaClass = object;
	/**
	 * Native Java BigDecimal (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/math/BigDecimal.html java.math.BigDecimal})
	 */
	type JavaBigDecimal = object;
	/**
	 * Native Java Set Object (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Set.html java.util.Set})
	 */
	type JavaSet = object;
	/**
	 * Native Java List Object (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/List.html java.util.List})
	 */
	type JavaList = object;
	/**
	 * Native Java Map Object (implementation of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Map.html java.util.Map})
	 */
	type JavaMap = object;
	/**
	 * Native Java Instant Object (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/Instant.html java.time.Instant})
	 */
	type JavaInstant = object;
	/**
	 * Native Java ZonedDateTime Object (instance of {@link https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/time/ZonedDateTime.html java.time.ZonedDateTime})
	 */
	type JavaZonedDateTime = object;
	/**
	 * Native Java openHAB State (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/types/state org.openhab.core.types.State})
	 */
	type HostState = object;
	/**
	 * Native Java openHAB Item (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/items/item org.openhab.core.items.Item})
	 */
	type HostItem = object;
	/**
	 * Native Java openHAB Rule (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/automation/rule org.openhab.core.automation.Rule})
	 */
	type HostRule = object;
	/**
	 * Native Java openHAB Trigger (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/automation/trigger org.openhab.core.automation.Trigger})
	 */
	type HostTrigger = object;
	/**
	 * Native Java openHAB Thing (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/thing/thing org.openhab.core.thing.Thing})
	 */
	type HostThing = object;
	/**
	 * Native Java openHAB GroupFunction (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/items/groupfunction org.openhab.core.items.GroupFunction})
	 */
	type HostGroupFunction = object;
	/**
	 * Native Java openHAB QuantityType (instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/library/types/quantitytype org.openhab.core.library.types.QuantityType})
	 */
	type QuantityType = object;
}
declare class ItemMetadata {
	/**
	 * Create an ItemMetadata instance, wrapping native openHAB Item metadata.
	 * @param {*} rawMetadata {@link https://www.openhab.org/javadoc/latest/org/openhab/core/items/metadata org.openhab.core.items.Metadata}
	 */
	constructor(rawMetadata: any);
	/**
	 * The metadata value.
	 * @type {string}
	 */
	value: string;
	/**
	 * The metadata configuration.
	 * @type {object}
	 */
	configuration: object;
	/**
	 * raw Java {@link https://www.openhab.org/javadoc/latest/org/openhab/core/items/metadata org.openhab.core.items.Metadata}
	 * @type {*}
	 */
	rawMetadata: any;
	/**
	 * The metadata key.
	 * @return {string}
	 */
	get key(): string;
	toString(): string;
}
declare class ItemPersistence {
	static PersistedItem: typeof PersistedItem;
	static PersistedState: typeof PersistedState;
	constructor(rawItem: any);
	rawItem: any;
	/**
	 * Persists a state of a given Item.
	 *
	 * There are six ways to use this method:
	 * ```js
	 * // Tell persistence to store the current Item state
	 * items.MyItem.persistence.persist();
	 * items.MyItem.persistence.persist('influxdb'); // using the InfluxDB persistence service
	 *
	 * // Tell persistence to store the state 'ON' at 2021-01-01 00:00:00
	 * items.MyItem.persistence.persist(time.toZDT('2021-01-01T00:00:00'), 'ON');
	 * items.MyItem.persistence.persist(time.toZDT('2021-01-01T00:00:00'), 'ON', 'influxdb'); // using the InfluxDB persistence service
	 *
	 * // Tell persistence to store a TimeSeries
	 * items.MyItem.persistence.persist(timeSeries);
	 * items.MyItem.persistence.persist(timeSeries, 'influxdb'); // using the InfluxDB persistence service
	 * ```
	 *
	 * **Note:** The persistence service will store the state asynchronously in the background, this method will return immediately.
	 * When storing the current state, this has the side effect, that if the Item state changes shortly the method call, the new state will be persisted.
	 * To work around that side effect, you might add `java.lang.Thread.sleep` to your code:
	 * ```js
	 * items.MyItem.persistence.persist(); // Tell persistence to store the current Item state
	 * java.lang.Thread.sleep(100); // Wait 100 ms to make sure persistence has enough time to store the current Item state
	 * items.MyItem.postUpdate(0); // Now set the Item state to a new value
	 * ```
	 *
	 * @param {(time.ZonedDateTime | Date)} [timestamp] the date for the item state to be stored
	 * @param {string|number|time.ZonedDateTime|Quantity|HostState} [state] the state to be stored
	 * @param {items.TimeSeries} [timeSeries] optional TimeSeries to be stored
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 */
	persist(timestamp?: (time.ZonedDateTime | Date), state?: string | number | time.ZonedDateTime | Quantity | HostState, timeSeries?: items.TimeSeries, serviceId?: string, ...args: any[]): void;
	/**
	 * Retrieves the persisted state for a given Item at a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time for which the persisted item should be retrieved
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} the {@link items.PersistedItem} at the given point in time, or <code>null</code> if no persisted item could be found
	 */
	persistedState(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Query the last update time of a given Item.
	 *
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(time.ZonedDateTime | null)} point in time of the last historic update to Item, or <code>null</code>
											  if the current state is different from the last persisted state or there are no historic persisted updates
	*/
	lastUpdate(serviceId?: string, ...args: any[]): (time.ZonedDateTime | null);
	/**
	 * Query the next update time of a given Item.
	 *
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(time.ZonedDateTime | null)} point in time of the first future update to Item, or <code>null</code> if there are no future persisted updates
	 */
	nextUpdate(serviceId?: string, ...args: any[]): (time.ZonedDateTime | null);
	/**
	 * Query the last change time of a given Item.
	 *
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(time.ZonedDateTime | null)} point in time of the last historic change to Item, or <code>null</code>
											  if the current state is different from the last persisted state or there are no historic persisted states
	 */
	lastChange(serviceId?: string, ...args: any[]): (time.ZonedDateTime | null);
	/**
	 * Query the next change time of a given Item.
	 *
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(time.ZonedDateTime | null)} point in time of the first future change to Item, or <code>null</code> if there are no future persisted states
	 */
	nextChange(serviceId?: string, ...args: any[]): (time.ZonedDateTime | null);
	/**
	 * Returns the previous state of a given Item.
	 *
	 * @param {boolean} [skipEqual] optional, if true, skips equal state values and searches the first state not equal the current state
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} the {@link items.PersistedItem} at the given point in time, or <code>null</code> if no persisted item could be found or null
	 */
	previousState(skipEqual?: boolean, serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Returns the next state of a given Item.
	 *
	 * @param {boolean} [skipEqual] optional, if true, skips equal state values and searches the first state not equal the current state
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} the {@link items.PersistedItem} at the given point in time, or <code>null</code> if no persisted item could be found or null
	 */
	nextState(skipEqual?: boolean, serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Checks if the state of a given Item has changed since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to start the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state has changed, <code>false</code> if it has not changed,
	 *                    <code>null</code> if <code>timestamp</code> is in the future
	 */
	changedSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Checks if the state of a given Item will change by a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to end the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state will change, <code>false</code> if it will not change,
	 *                    <code>null</code> if <code>timestamp></code> is in the past
	 */
	changedUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Checks if the state of a given Item has changed between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time to start the check
	 * @param {(time.ZonedDateTime | Date)} end the point in time to stop the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state changes, <code>false</code> if the item does not change in the given interval,
	 *                    <code>null</code> if <code>begin</code> is after <code>end</code>
	 */
	changedBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Checks if the state of a given Item has been updated since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to start the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state was updated, <code>false</code> if the item has not been updated since <code>timestamp</code>,
	 *                    <code>null</code> if <code>timestamp</code> is in the future
	 */
	updatedSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Checks if the state of a given Item will have been updated until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to end the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state is updated, <code>false</code> if the item is not updated until <code>timestamp</code>,
	 *                    <code>null</code> if <code>timestamp</code> is in the past
	 */
	updatedUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Checks if the state of a given Item has been updated between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time to start the check
	 * @param {(time.ZonedDateTime | Date)} end the point in time to stop the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {boolean} <code>true</code> if item state was updated, <code>false</code> if the item has not been updated in the given interval,
	 *                    <code>null</code> if <code>begin</code> is after <code>end</code>
	 */
	updatedBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): boolean;
	/**
	 * Gets the historic Item with the maximum value of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to start the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem} with the maximum state value since the given point in time,
	 *                                   or <code>null</code> if <code>timestamp</code> is in the future
	 */
	maximumSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the future Item with the maximum value of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to end the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem}m with the maximum state value until the given point in time,
	 *                                   or <code>null</code> if <code>timestamp</code> is in the past
	 */
	maximumUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the persisted Item with the maximum value of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time to start the check
	 * @param {(time.ZonedDateTime | Date)} end the point in time to stop the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem} with the maximum state value between two points in time,
	 *                                   or <code>null</code> if <code>begin</code> is after <code>end</end>
	 */
	maximumBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the historic Item with the minimum value of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to start the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem} with the minimum state value since the given point in time,
	 *                                   or <code>null</code> if <code>timestamp</code> is in the future
	 */
	minimumSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the future Item with the minimum value of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to end the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem} with the minimum state value until the given point in time,
	 *                                   or <code>null</code> if <code>timestamp</code> is in the past
	 */
	minimumUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the state with the minimum value of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time to start the check
	 * @param {(time.ZonedDateTime | Date)} end the point in time to stop the check
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedItem | null)} a {@link items.PersistedItem} with the minimum state value between two points in time,
	 *                                   or <code>null</code> if <code>begin</code> is after <code>end</end>
	 */
	minimumBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedItem | null);
	/**
	 * Gets the variance of the state of the given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to compute the variance
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the variance between then and now as {@link items.PersistedState}, or <code>null</code> if
	 *                            <code>timestamp</code> is in the future, or if there is no persisted state for the given
	 *                            Item at the given <code>timestamp</code>
	 */
	varianceSince(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the variance of the state of the given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to compute the variance
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the variance between now and then as {@link items.PersistedState}, or <code>null</code> if
	 *                            <code>timestamp</code> is in the past, or if there is no persisted state for the given
	 *                            Item at the given <code>timestamp</code>
	 */
	varianceUntil(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the variance of the state of the given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to compute the variance
	 * @param {(time.ZonedDateTime | Date)} end the end time for the computation
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the variance between both points of time as {@link items.PersistedState}, or <code>null</code> if
	 *                            <code>begin</code> is after <code>end</code>, or if there is no persisted state for the given
	 *                            Item between <code>begin</code> and <code>end</code>
	 */
	varianceBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the standard deviation of the state of the given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to compute the standard deviation
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the standard deviation between then and now as {@link items.PersistedState}, or <code>null</code>
	 *                            if <code>timestamp</code> is in the future, or if there is no persisted state for the given Item
	 *                            at the given <code>timestamp</code>
	 */
	deviationSince(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the standard deviation of the state of the given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to compute the standard deviation
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the standard deviation between now and then as {@link items.PersistedState}, or <code>null</code>
	 *                            if <code>timestamp</code> is in the past, or if there is no persisted state for the given Item
	 *                            at the given <code>timestamp</code>
	 */
	deviationUntil(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the standard deviation of the state of the given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to compute
	 * @param {(time.ZonedDateTime | Date)} end the end time for the computation
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the standard deviation between both points of time as {@link items.PersistedState}, or <code>null</code>
	 *                            if <code>begin</code> is after <code>end</code>, or if there is no persisted state for the given Item
	 *                            between <code>begin</code> and <code>end</code>
	 */
	deviationBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the average value of the state of a given Item since a certain point in time.
	 *
	 * @example
	 * var yesterday = time.toZDT().minusDays(1);
	 * var item = items.getItem('KitchenDimmer');
	 * console.log('KitchenDimmer average since yesterday', item.persistence.averageSince(yesterday));
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to search for the average value
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the average value since <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no previous states could be found
	 */
	averageSince(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the average value of the state of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to search for the average value
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the average value until <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no future states could be found
	 */
	averageUntil(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the average value of the state of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to start the average
	 * @param {(time.ZonedDateTime | Date)} end the point in time to which to start the average
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the average value between <code>begin</code> and <code>end</code> as {@link items.PersistedState} or <code>null</code> if no states could be found
	 */
	averageBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the Riemann sum of the states of a given Item since a certain point in time, time is calculated in seconds.
	 *
	 * @example
	 * var yesterday = time.toZDT().minusDays(1);
	 * var item = items.getItem('SolarPower');
	 * console.log('Solar energy production since yesterday', item.persistence.riemannSumSince(yesterday));
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to search for the Riemann sum
	 * @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	 *                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	 *                                    default <code>LEFT</code>
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the Riemann sum since <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no previous states could be found, time is calculated in seconds
	 */
	riemannSumSince(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	* Gets the Riemann sum of the states of a given Item until a certain point in time, time is calculated in seconds.
	*
	* @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to search for the Riemann sum
	* @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	*                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	*                                    default <code>LEFT</code>
	* @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	* @returns {(PersistedState | null)} the Riemann sum until <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no future states could be found, time is calculated in seconds
	*/
	riemannSumUntil(timestamp: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	* Gets the Riemann sum of the states of a given Item between two certain points in time, time is calculated in seconds.
	*
	* @param {(time.ZonedDateTime | Date)} begin the point in time from which to start the Riemann sum
	* @param {(time.ZonedDateTime | Date)} end the point in time to which to start the Riemann sum
	* @param {RiemannType} [riemannType] optional Riemann approximation type to calculate the integral approximation
	*                                    (<code>LEFT</code>, <code>RIGHT</code>, <code>TRAPEZOIDAL</code>, <code>MIDPOINT</code>),
	*                                    default <code>LEFT</code>
	* @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	* @returns {(PersistedState | null)} the Riemann sum between <code>begin</code> and <code>end</code> as {@link items.PersistedState} or <code>null</code> if no states could be found, time is calculated in seconds
	*/
	riemannSumBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), riemannType?: any, serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the median value of the state of a given Item since a certain point in time.
	 *
	 * @example
	 * var yesterday = time.toZDT().minusDays(1);
	 * var item = items.getItem('KitchenDimmer');
	 * console.log('KitchenDimmer median since yesterday', item.persistence.medianSince(yesterday));
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to search for the median value
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the median value since <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no previous states could be found
	 */
	medianSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the median value of the state of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to search for the median value
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the median value until <code>timestamp</code> as {@link items.PersistedState} or <code>null</code> if no future states could be found
	 */
	medianUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the median value of the state of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to start the median
	 * @param {(time.ZonedDateTime | Date)} end the point in time to which to start the median
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the median value between <code>begin</code> and <code>end</code> as {@link items.PersistedState} or <code>null</code> if no states could be found
	 */
	medianBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the sum of the states of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to start the summation
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the sum of the state values since <code>timestamp</code> as {@link items.PersistedState}, or null if <code>timestamp</code> is in the future
	 */
	sumSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the sum of the states of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to start the summation
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the sum of the state values until <code>timestamp</code> as {@link items.PersistedState}, or null if <code>timestamp</code> is in the past
	 */
	sumUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the sum of the states of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to start the summation
	 * @param {(time.ZonedDateTime | Date)} end the point in time to which to start the summation
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the sum of the state values between the given points in time as {@link items.PersistedState},
	 *                            or null if <code>begin</code> is after <code>end</code>
	 */
	sumBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the difference value of the state of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to compute the delta
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the difference between now and then as {@link items.PersistedState}, or <code>null</code>
	 *                            if there is no persisted state for the given Item at the given <code>timestamp</code> available
	 */
	deltaSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the difference value of the state of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to compute the delta
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the difference between then and now as {@link items.PersistedState}, or <code>null</code>
	 *                            if there is no persisted state for the given Item at the given <code>timestamp</code> available
	 */
	deltaUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the difference value of the state of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the beginning point in time
	 * @param {(time.ZonedDateTime | Date)} end the end point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(PersistedState | null)} the difference between end and begin as {@link items.PersistedState}, or <code>null</code>
	 *                            if there is no persisted state for the given Item for the given points in time
	 */
	deltaBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (PersistedState | null);
	/**
	 * Gets the evolution rate of the state of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to compute the evolution rate
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(number | null)} the evolution rate in percent (positive and negative) between then and now, or <code>null</code>
	 *                            if there is no persisted state for the given Item at the given <code>timestamp</code>,
	 *                            or if there is a state, but it is zero (which would cause a divide-by-zero error)
	 */
	evolutionRateSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (number | null);
	/**
	 * Gets the evolution rate of the state of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to compute the evolution rate
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(number | null)} the evolution rate in percent (positive and negative) between then and now, or <code>null</code>
	 *                            if there is no persisted state for the given Item at the given <code>timestamp</code>,
	 *                            or if there is a state, but it is zero (which would cause a divide-by-zero error)
	 */
	evolutionRateUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (number | null);
	/**
	 * Gets the evolution rate of the state of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the beginning point in time
	 * @param {(time.ZonedDateTime | Date)} end the end point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {(number | null)} the evolution rate in percent (positive and negative) in the given interval, or <code>null</code>
	 *                            if there are no persisted states for the given Item at the given interval, or if there is a state,
	 *                            but it is zero (which would cause a divide-by-zero error)
	 */
	evolutionRateBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): (number | null);
	/**
	 * Gets the number of available historic data points of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the beginning point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of values persisted for this item, <code>null</code> if <code>timestamp</code> is in the future
	 */
	countSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Gets the number of available future data points of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the ending point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of values persisted for this item, <code>null</code> if <code>timestamp</code> is in the past
	 */
	countUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Gets the number of available persisted data points of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the beginning point in time
	 * @param {(time.ZonedDateTime | Date)} end the end point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of values persisted for this item, <code>null</code> if <code>begin</code> is after <code>end</code>
	 */
	countBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Gets the number of changes in historic data points of a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the beginning point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of state changes for this item
	 */
	countStateChangesSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Gets the number of changes in future data points of a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the ending point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of state changes for this item
	 */
	countStateChangesUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Gets the number of changes in persisted data points of a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the beginning point in time
	 * @param {(time.ZonedDateTime | Date)} end the end point in time
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {number} the number of state changes for this item
	 */
	countStateChangesBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): number;
	/**
	 * Retrieves the historic Items for a given Item since a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to retrieve the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {PersistedItem[]} the {@link items.PersistedItem}s since the given point in time
	 */
	getAllStatesSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): PersistedItem[];
	/**
	 * Retrieves the future Items for a given Item until a certain point in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to retrieve the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {PersistedItem[]} the future {@link items.PersistedItem}s to the given point in time
	 */
	getAllStatesUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): PersistedItem[];
	/**
	 * Retrieves the persisted Items for a given Item between two certain points in time.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to retrieve the states
	 * @param {(time.ZonedDateTime | Date)} end the point in time to which to retrieve the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 * @returns {PersistedItem[]} the historic {@link items.PersistedItem}s between the given points in time,
	 */
	getAllStatesBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): PersistedItem[];
	/**
	 * Removes from persistence the historic items for a given Item since a certain point in time.
	 * This will only have effect if the persistence service is a modifiable persistence service.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time from which to remove the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 */
	removeAllStatesSince(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): any;
	/**
	 * Removes from persistence the future items for a given Item until a certain point in time.
	 * This will only have effect if the persistence service is a modifiable persistence service.
	 *
	 * @param {(time.ZonedDateTime | Date)} timestamp the point in time to which to remove the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 */
	removeAllStatesUntil(timestamp: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): any;
	/**
	 * Removes from persistence the persisted items for a given Item between two certain points in time.
	 * This will only have effect if the persistence service is a modifiable persistence service.
	 *
	 * @param {(time.ZonedDateTime | Date)} begin the point in time from which to remove the states
	 * @param {(time.ZonedDateTime | Date)} end the point in time to which to remove the states
	 * @param {string} [serviceId] optional persistence service ID, if omitted, the default persistence service will be used
	 */
	removeAllStatesBetween(begin: (time.ZonedDateTime | Date), end: (time.ZonedDateTime | Date), serviceId?: string, ...args: any[]): any;
	#private;
}
declare namespace ItemPersistence {
	type RiemannType = {
		LEFT: string;
		RIGHT: string;
		TRAPEZOIDAL: string;
		MIDPOINT: string;
	};
	const RiemannType: ItemPersistence.RiemannType;
}
declare class PersistedItem extends PersistedState {
	rawHistoricItem: any;
	/**
	 * Timestamp of persisted Item.
	 *
	 * Consider using {@link instant} for heavy calculations because it is much faster to work with Instant.
	 * @type {time.ZonedDateTime}
	 */
	get timestamp(): time.ZonedDateTime;
	/**
	 * Timestamp of the persisted Item as Instant.
	 * @returns {time.Instant}
	 */
	get instant(): time.Instant;
}
declare class PersistedState {
	/**
	 * Create an PersistedState, wrapping a native openHAB HistoricState.
	 * @param {*} rawHistoricState an instance of {@link https://www.openhab.org/javadoc/latest/org/openhab/core/types/state org.openhab.core.types.State}
	 * @hideconstructor
	 */
	constructor(rawHistoricState: any);
	rawState: any;
	/**
	 * String representation of the Item state.
	 * @type {string}
	 */
	get state(): string;
	/**
	 * Numeric representation of Item state, or `null` if state is not numeric
	 * @type {number|null}
	 */
	get numericState(): number | null;
	/**
	 * Item state as {@link Quantity} or `null` if state is not Quantity-compatible or Quantity would be unit-less (without unit)
	 * @type {Quantity|null}
	 */
	get quantityState(): Quantity | null;
	toString(): string;
}
declare class ItemSemantics {
	constructor(rawItem: any, getItem: any);
	rawItem: any;
	getItem: any;
	/**
	 * The type of the semantic equipment or `null` if none is set.
	 * @type {string|null}
	 */
	get equipmentType(): string | null;
	/**
	 * The type of the semantic location or `null` if none is set.
	 * @type {string|null}
	 */
	get locationType(): string | null;
	/**
	 * The type of the semantic point or `null` if none is set.
	 * @type {string|null}
	 */
	get pointType(): string | null;
	/**
	 * The type of the semantic property or `null` if none is set.
	 * @type {string|null}
	 */
	get propertyType(): string | null;
	/**
	 * Determines the semantic type (i.e. a subtype of Location, Equipment or Point) or `null` if no semantics are set.
	 * @type {string|null}
	 */
	get semanticType(): string | null;
	/**
	 * Whether the Item is a Location
	 * @type {boolean}
	 */
	get isLocation(): boolean;
	/**
	 * Whether the Item is an Equipment
	 * @type {boolean}
	 */
	get isEquipment(): boolean;
	/**
	 * Whether the Item is a Point
	 * @type {boolean}
	 */
	get isPoint(): boolean;
	/**
	 * The Location Item where this Item is situated or `null` if it's not in a Location.
	 * @type {items.Item|null}
	 */
	get location(): items.Item | null;
	/**
	 * The Equipment Item where this Item is situated or `null` if it's not in an Equipment.
	 * @type {items.Item|null}
	 */
	get equipment(): items.Item | null;
}
/**
 * configuration describing an Item
 */
export type ItemConfig = {
	/**
	 * the type of the Item
	 */
	type: string;
	/**
	 * Item name for the Item to create
	 */
	name: string;
	/**
	 * the label for the Item
	 */
	label?: string | undefined;
	/**
	 * the category (icon) for the Item
	 */
	category?: string | undefined;
	/**
	 * an array of groups the Item is a member of
	 */
	groups?: string[] | undefined;
	/**
	 * an array of tags for the Item
	 */
	tags?: string[] | undefined;
	/**
	 * group configuration, only applicable if type is `Group`
	 */
	group?: {
		/**
		 * the type of the Group, such as `Switch` or `Number`
		 */
		type: string;
		/**
		 * the group function, such as 'EQUALITY' or `AND`
		 */
		function?: string | undefined;
		/**
		 * optional parameters for the group function, e.g. `ON` and `OFF` for the `AND` function
		 */
		parameters?: string[] | undefined;
	} | undefined;
	/**
	 * for single channel link a string or for multiple an object { channeluid: configuration }; configuration is an object
	 */
	channels?: string | object;
	/**
	 * either object `{ namespace: value }` or `{ namespace: `{@link items.ItemMetadata}` }`
	 */
	metadata?: any;
	/**
	 * short form for the stateDescription metadata's pattern configuration
	 */
	format?: string | undefined;
	/**
	 * short form for the unit metadata's value
	 */
	unit?: string | undefined;
	/**
	 * short form for the autoupdate metadata's value
	 */
	autoupdate?: boolean | undefined;
};
declare class Item {
	/**
	 * Create an Item, wrapping a native Java openHAB Item. Don't use this constructor, instead call {@link getItem}.
	 * @param {HostItem} rawItem Java Item from Host
	 */
	constructor(rawItem: HostItem);
	/**
	 * raw Java {@link https://www.openhab.org/javadoc/latest/org/openhab/core/items/item org.openhab.core.items.Item}
	 * @type {HostItem}
	 */
	rawItem: HostItem;
	/**
	 * Access historical states for this Item {@link items.ItemPersistence}
	 * @type {ItemPersistence}
	 */
	persistence: ItemPersistence;
	/**
	 * Access Semantic information of this Item {@link items.ItemSemantics}
	 * @type {ItemSemantics}
	 */
	semantics: ItemSemantics;
	/**
	 * Type of Item: the Simple (without package) name of the Java Item type, such as 'Switch'.
	 * @type {string}
	 */
	get type(): string;
	/**
	 * Type of the Group, if this Item is a Group and has a type, else `null`.
	 * @type {string|null}
	 */
	get groupType(): string | null;
	/**
	 * Name of Item
	 * @type {string}
	 */
	get name(): string;
	/**
	 * Label attached to Item, or `null` if not set
	 * @type {string|null}
	 */
	get label(): string | null;
	/**
	 * Category of the Item, or `null` if not set
	 * @return {string|null}
	 */
	get category(): string | null;
	/**
	 * String representation of the Item state, or `null` if not available
	 * @type {string|null}
	 */
	get state(): string | null;
	/**
	 * Numeric representation of Item state, or `null` if state is not numeric
	 * @type {number|null}
	 */
	get numericState(): number | null;
	/**
	 * Item state as {@link Quantity} or `null` if state is not Quantity-compatible or Quantity would be unit-less (without unit)
	 * @type {Quantity|null}
	 */
	get quantityState(): Quantity | null;
	/**
	 * Item state as boolean or `null` if state is not boolean-compatible.
	 * @type {boolean|null}
	 */
	get boolState(): boolean | null;
	/**
	 * Raw state of Item, as a Java {@link https://www.openhab.org/javadoc/latest/org/openhab/core/types/state State object}
	 * @type {HostState|null}
	 */
	get rawState(): HostState | null;
	/**
	 * String representation of the previous state of the Item or `null` if no previous state is available.
	 * @type {string|null}
	 */
	get previousState(): string | null;
	/**
	 * Numeric representation of Item previous state, or `null` if state is not numeric or not available.
	 * @type {number|null}
	 */
	get previousNumericState(): number | null;
	/**
	 * Previous item state as {@link Quantity} or `null` if state is not Quantity-compatible, Quantity would be unit-less (without unit) or not available.
	 * @type {Quantity|null}
	 */
	get previousQuantityState(): Quantity | null;
	/**
	  * Previous raw state of Item, as a Java {@link https://www.openhab.org/javadoc/latest/org/openhab/core/types/state State object} or `null` if previous state not available.
	 * @type {HostState|null}
	 */
	get previousRawState(): HostState | null;
	/**
	 * The time the state was last updated as ZonedDateTime or `null` if no timestamp is available.
	 * @type {time.ZonedDateTime|null}
	 */
	get lastStateUpdateTimestamp(): time.ZonedDateTime | null;
	/**
	 * The time the state was last updated as Instant or `null` if no timestamp is available.
	 * @type {time.Instant|null}
	 */
	get lastStateUpdateInstant(): time.Instant | null;
	/**
	 * The time the state was last changed as ZonedDateTime or `null` if no timestamp is available.
	 * @type {time.ZonedDateTime|null}
	 */
	get lastStateChangeTimestamp(): time.ZonedDateTime | null;
	/**
	 * The time the state was last changed as Instant or `null` if no timestamp is available.
	 * @type {time.Instant|null}
	 */
	get lastStateChangeInstant(): time.Instant | null;
	/**
	 * Members / children / direct descendents of the current group Item (as returned by 'getMembers()'). Must be a group Item.
	 * @type {Item[]}
	 */
	get members(): Item[];
	/**
	 * All descendents of the current group Item (as returned by 'getAllMembers()'). Must be a group Item.
	 * @type {Item[]}
	 */
	get descendents(): Item[];
	/**
	 * Whether this Item is initialized (`true` if it has been initialized).
	 * @type {boolean}
	 */
	get isInitialized(): boolean;
	/**
	 * Whether this Item is uninitialized (`true` if it has not been initialized).
	 * @deprecated use {@link isInitialized} instead
	 * @type {boolean}
	 */
	get isUninitialized(): boolean;
	/**
	 * Gets metadata of a single namespace or of all namespaces from this Item.
	 *
	 * @example
	 * // Get metadata of ALL namespaces
	 * var meta = Item.getMetadata();
	 * var namespaces = Object.keys(meta); // Get metadata namespaces
	 * // Get metadata of a single namespace
	 * meta = Item.getMetadata('expire');
	 *
	 * @see items.metadata.getMetadata
	 * @param {string} [namespace] name of the metadata: if provided, only metadata of this namespace is returned, else all metadata is returned
	 * @returns {{ namespace: items.ItemMetadata }|items.ItemMetadata|null} all metadata as an object with the namespaces as properties OR metadata of a single namespace or `null` if that namespace doesn't exist; the metadata itself is of type {@link items.ItemMetadata}
	 */
	getMetadata(namespace?: string): {
		namespace: items.ItemMetadata;
	} | items.ItemMetadata | null;
	/**
	 * Updates or adds metadata of a single namespace to this Item.
	 *
	 * If metadata is not provided by this script or the ManagedMetadataProvider, it is not editable and a warning is logged.
	 *
	 * @see items.metadata.replaceMetadata
	 * @param {string} namespace name of the metadata
	 * @param {string} value value for this metadata
	 * @param {object} [configuration] optional metadata configuration
	 * @returns {items.ItemMetadata|null} old {@link items.metadata.ItemMetadata} or `null` if the Item has no metadata with the given name
	 */
	replaceMetadata(namespace: string, value: string, configuration?: object): items.ItemMetadata | null;
	/**
	 * Removes metadata of a single namespace or of all namespaces from a given Item.
	 *
	 * @see items.metadata.removeMetadata
	 * @param {string} [namespace] name of the metadata: if provided, only metadata of this namespace is removed, else all metadata is removed
	 * @returns {items.ItemMetadata|null} removed {@link items.metadata.ItemMetadata} OR `null` if the Item has no metadata under the given namespace or all metadata was removed
	 */
	removeMetadata(namespace?: string): items.ItemMetadata | null;
	/**
	 * Sends a command to the Item.
	 *
	 * @example
	 * // Turn on the Hallway lights
	 * items.getItem('HallwayLight').sendCommand('ON');
	 * // Turn on the Hallway lights for at least 5 minutes, if they were on before, keep them on, otherwise turn them off
	 * items.getItem('HallwayLight').sendCommand('ON', time.Duration.ofMinutes(5));
	 * // Turn on the Hallway lights for 5 minutes, then turn them off
	 * items.getItem('HallwayLight').sendCommand('ON', time.Duration.ofMinutes(5), 'OFF');
	 *
	 * @param {string|number|time.ZonedDateTime|time.Instant|Quantity|HostState|null} value the value of the command to send, such as 'ON'
	 * @param {time.Duration} [expire] optional duration (see {@link https://js-joda.github.io/js-joda/class/packages/core/src/Duration.js~Duration.html JS-Joda: Duration}) after which the command expires and the Item is commanded back to its previous state or `onExpire`
	 * @param {string|number|time.ZonedDateTime|time.Instant|Quantity|HostState} [onExpire] the optional value of the command to apply on expire, default is the current state
	 * @see sendCommandIfDifferent
	 * @see postUpdate
	 */
	sendCommand(value: string | number | time.ZonedDateTime | time.Instant | Quantity | HostState | null, expire?: time.Duration, onExpire?: string | number | time.ZonedDateTime | time.Instant | Quantity | HostState): void;
	/**
	 * Sends a command to the Item, but only if the current state is not what is being sent.
	 *
	 * @param {string|number|time.ZonedDateTime|time.Instant|Quantity|HostState} value the value of the command to send, such as 'ON'
	 * @returns {boolean} true if the command was sent, false otherwise
	 * @see sendCommand
	 */
	sendCommandIfDifferent(value: string | number | time.ZonedDateTime | time.Instant | Quantity | HostState): boolean;
	/**
	 * Increase the value of this Item to the given value by sending a command, but only if the current state is less than that value.
	 *
	 * @param {number|Quantity|HostState} value the value of the command to send, such as 'ON'
	 * @return {boolean} true if the command was sent, false otherwise
	 */
	sendIncreaseCommand(value: number | Quantity | HostState): boolean;
	/**
	 * Decreases the value of this Item to the given value by sending a command, but only if the current state is greater than that value.
	 *
	 * @param {number|Quantity|HostState} value the value of the command to send, such as 'ON'
	 * @return {boolean} true if the command was sent, false otherwise
	 */
	sendDecreaseCommand(value: number | Quantity | HostState): boolean;
	/**
	 * Calculates the toggled state of this Item.
	 * For Items like Color and Dimmer, getStateAs(OnOffType) is used and the toggle calculated of that.
	 *
	 * @ignore
	 * @returns the toggled state (e.g. 'OFF' if the Item is 'ON')
	 * @throws error if the Item is uninitialized or is a type that doesn't make sense to toggle
	 */
	getToggleState(): "OPEN" | "PLAY" | "ON" | "PAUSE" | "CLOSED" | "OFF";
	/**
	 * Sends a command to flip the Item's state (e.g. if it is 'ON' an 'OFF' command is sent).
	 * @throws error if the Item is uninitialized or a type that cannot be toggled or commanded
	 */
	sendToggleCommand(): void;
	/**
	 * Posts an update to flip the Item's state (e.g. if it is 'ON' an 'OFF'
	 * update is posted).
	 * @throws error if the Item is uninitialized or a type that cannot be toggled
	 */
	postToggleUpdate(): void;
	/**
	 * Posts an update to the Item.
	 *
	 * @param {string|number|time.ZonedDateTime|time.Instant|Quantity|HostState|null} value the value of the command to send, such as 'ON'
	 * @see postToggleUpdate
	 * @see sendCommand
	 */
	postUpdate(value: string | number | time.ZonedDateTime | time.Instant | Quantity | HostState | null): void;
	/**
	 * Gets the names of the groups this Item is member of.
	 * @returns {string[]}
	 */
	get groupNames(): string[];
	/**
	 * Adds groups to this Item
	 * @param {...string|...Item} groupNamesOrItems one or more names of the groups (or the group Items themselves)
	 */
	addGroups(...groupNamesOrItems: any[]): void;
	/**
	 * Removes groups from this Item
	 * @param {...string|...Item} groupNamesOrItems one or more names of the groups (or the group Items themselves)
	 */
	removeGroups(...groupNamesOrItems: any[]): void;
	/**
	 * Gets the tags from this Item
	 * @type {string[]}
	 */
	get tags(): string[];
	/**
	 * Adds tags to this Item
	 * @param {...string} tagNames names of the tags to add
	 */
	addTags(...tagNames: string[]): void;
	/**
	 * Removes tags from this Item
	 * @param {...string} tagNames names of the tags to remove
	 */
	removeTags(...tagNames: string[]): void;
	toString(): string;
}
/**
 * When a rule is triggered, the script is provided the event instance that triggered it. The specific data depends on the event type. The `EventObject` provides several information about that trigger.
 *
 * Note:
 * `Group****Trigger`s use the equivalent `Item****Trigger` as trigger for each member.
 * Time triggers do not provide any event instance, therefore no property is populated.
 */
export type EventObject = {
	/**
	 * only for {@link triggers.ItemStateChangeTrigger} & {@link triggers.GroupStateChangeTrigger}: Previous state of Item or Group that triggered event
	 */
	oldState: string;
	/**
	 * only for {@link triggers.ItemStateChangeTrigger} & {@link triggers.GroupStateChangeTrigger}: New state of Item or Group that triggered event
	 */
	newState: string;
	/**
	 * only for {@link triggers.ItemStateUpdateTrigger} & {@link triggers.GroupStateUpdateTrigger}: State that triggered event
	 */
	receivedState: string;
	/**
	 * only for {@link triggers.ItemCommandTrigger}, {@link triggers.GroupCommandTrigger}, {@link triggers.PWMTrigger} & {@link triggers.PIDTrigger} : Command that triggered event
	 */
	receivedCommand: string;
	/**
	 * for all Item-related triggers: name of Item that triggered event
	 */
	itemName: string;
	/**
	 * for all `Group****Trigger`s: name of the group whose member triggered event
	 */
	groupName: string;
	/**
	 * only for {@link triggers.ChannelEventTrigger}: Channel event that triggered event
	 */
	receivedEvent: string;
	/**
	 * only for {@link triggers.ChannelEventTrigger}: UID of channel that triggered event
	 */
	channelUID: string;
	/**
	 * only for {@link triggers.ThingStatusChangeTrigger}: Previous state of Thing that triggered event
	 */
	oldStatus: string;
	/**
	 * only for {@link triggers.ThingStatusChangeTrigger}: New state of Thing that triggered event
	 */
	newStatus: string;
	/**
	 * only for {@link triggers.ThingStatusUpdateTrigger}: State of Thing that triggered event
	 */
	status: string;
	/**
	 * for all Thing-related triggers: UID of Thing that triggered event
	 */
	thingUID: string;
	/**
	 * for {@link triggers.GenericCronTrigger}: cron expression of the trigger
	 */
	cronExpression: string;
	/**
	 * for {@link triggers.TimeOfDayTrigger}: time of day value of the trigger
	 */
	time: string;
	/**
	 * for {@link triggers.DateTimeTrigger}: whether the trigger only considers the time part of the DateTime Item
	 */
	timeOnly: boolean;
	/**
	 * for {@link triggers.DateTimeTrigger}: offset in seconds added to the time of the DateTime Item
	 */
	offset: number;
	/**
	 * for all triggers except {@link triggers.PWMTrigger}, {@link triggers.PIDTrigger}: Type of event that triggered event (change, command, time, triggered, update, time)
	 */
	eventType: string;
	/**
	 * for all triggers except {@link triggers.PWMTrigger}, {@link triggers.PIDTrigger}: Type of trigger that triggered event
	 */
	triggerType: string;
	/**
	 * for all triggers: simple Java class name of the triggering event
	 */
	eventName: string;
	/**
	 * for all triggers: full Java class name of the triggering event
	 */
	eventClass: string;
	/**
	 * for all triggers: topic of the triggering event
	 */
	eventTopic: string;
	/**
	 * for all triggers: source of the triggering event or null if not specified
	 */
	eventSource: string | null;
	/**
	 * (user-defined or auto-generated) name of trigger
	 */
	module: string;
	/**
	 * original contents of the event including data passed from a calling rule
	 */
	raw: any;
	/**
	 * if provided by event: payload of event in Java data types
	 */
	payload: any;
};
/**
 * When a rule is run, a callback is executed.
 */
export type RuleCallback = (event: EventObject) => any;
export type RuleConfig = {
	/**
	 * name of the rule (used in UI)
	 */
	name: string;
	/**
	 * description of the rule (used in UI)
	 */
	description?: string | undefined;
	/**
	 * which will fire the rule
	 */
	triggers?: object | object[] | undefined;
	/**
	 * callback to run when the rule fires
	 */
	execute: RuleCallback;
	/**
	 * tags for the rule (used in UI)
	 */
	tags?: string[] | undefined;
	/**
	 * UID of the rule, if not provided, one is generated
	 */
	id?: string | undefined;
	/**
	 * whether to overwrite an existing rule with the same UID
	 */
	overwrite?: boolean | undefined;
	/**
	 * whether to run the rule in a separate dedicated context
	 */
	dedicatedContext?: boolean | undefined;
	/**
	 * (optional and only for {@link SwitchableJSRule}) name of the switch Item, which will get created automatically if it is not existent
	 */
	switchItemName?: string | undefined;
	/**
	 * (optional and only for {@link SwitchableJSRule}) name of an Item group to use for the switch Item, which will get created automatically if it is not existent
	 */
	ruleGroup?: string | undefined;
};
declare function getQuantity(value: items.Item | string | Quantity$1 | QuantityType): Quantity$1;
declare class Quantity$1 {
	/**
	 * @param {items.Item|string|Quantity|QuantityType} value
	 */
	constructor(value: items.Item | string | Quantity$1 | QuantityType);
	/**
	 * @type {QuantityType}
	 * @private
	 */
	private rawQtyType;
	/**
	 * Dimension of this Quantity, e.g. `[L]` for metres or `[L]²` for cubic-metres
	 * @type {string}
	 */
	get dimension(): string;
	/**
	 * Unit name of this Quantity, e.g. `Metre`, `kWh`, or `null` if not available
	 * @type {string|null}
	 */
	get unit(): string | null;
	/**
	 * Unit symbol of this Quantity, e.g. `m`, `kWh`, or `null` if not available
	 * @type {string|null}
	 */
	get symbol(): string | null;
	/**
	 * Float (decimal number) value of this Quantity
	 * @type {number}
	 */
	get float(): number;
	/**
	 * Integer (non-decimal number) value of this Quantity
	 * @type {number}
	 */
	get int(): number;
	/**
	 * Add the given value to this Quantity.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {Quantity} result as new Quantity
	 */
	add(value: items.Item | string | Quantity$1): Quantity$1;
	/**
	 * Divide this Quantity by the given value.
	 *
	 * @example
	 * Quantity('20 W').divide(4); // is 5 W
	 * Quantity('20 W').divide('4 W') // is 5
	 *
	 * @param {items.Item|number|string|Quantity} value usually a number; may also be an {@link items.Item} which is either Quantity-compatible or holds a number, a `string` consisting of amount and unit or a {@link Quantity}, but be careful: 1 W / 5 W = 0.2 which might not be what you want
	 * @returns {Quantity} result as new Quantity
	 */
	divide(value: items.Item | number | string | Quantity$1): Quantity$1;
	/**
	 * Multiply this Quantity by the given value.
	 *
	 * @example
	 * Quantity('20 W').multiply(4); // is 80 W
	 * Quantity('20 W').multiply('4 W') // is 80 W^2
	 *
	 * @param {items.Item|number|string|Quantity} value usually a number; may also be an {@link items.Item} which is either Quantity-compatible or holds a number, a `string` consisting of amount and unit or a {@link Quantity}, but be careful: 1 W * 5 W = 5 W^2 which might not be what you want
	 * @returns {Quantity} result as new Quantity
	 */
	multiply(value: items.Item | number | string | Quantity$1): Quantity$1;
	/**
	 * Subtract the given value from this Quantity.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {Quantity} result as new Quantity
	 */
	subtract(value: items.Item | string | Quantity$1): Quantity$1;
	/**
	 * Convert this Quantity to the given unit.
	 *
	 * @param {string} unit
	 * @returns {Quantity|null} a new Quantity with the given unit or `null` if conversion to this unit is not possible
	 * @throws {QuantityError} when unit cannot be parsed because it is invalid
	 */
	toUnit(unit: string): Quantity$1 | null;
	/**
	 * Checks whether this Quantity is equal to the passed in value.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {boolean}
	 */
	equal(value: items.Item | string | Quantity$1): boolean;
	/**
	 * Checks whether this Quantity is larger than the passed in value.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {boolean}
	 */
	greaterThan(value: items.Item | string | Quantity$1): boolean;
	/**
	 * Checks whether this Quantity is larger than or equal to the passed in value.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {boolean}
	 */
	greaterThanOrEqual(value: items.Item | string | Quantity$1): boolean;
	/**
	 * Checks whether this Quantity is smaller than the passed in value.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {boolean}
	 */
	lessThan(value: items.Item | string | Quantity$1): boolean;
	/**
	 * Checks whether this Quantity is smaller than or equal to the passed in value.
	 *
	 * @param {items.Item|string|Quantity} value Quantity-compatible {@link items.Item}, `string` consisting of amount and unit or a {@link Quantity}
	 * @returns {boolean}
	 */
	lessThanOrEqual(value: items.Item | string | Quantity$1): boolean;
	toString(): string;
}
declare global {
	namespace items {
		type Item = Item;
		type ItemConfig = ItemConfig;
		type ItemMetadata = ItemMetadata;
		type TimeSeries = import("./items/time-series");
		type ItemPersistence = ItemPersistence;
		type ItemSemantics = ItemSemantics;
		type PersistedItem = InstanceType<typeof PersistedItem>;
		type PersistedState = InstanceType<typeof PersistedState>;
	}
	namespace time {
		type ZonedDateTime = import("@js-joda/core").ZonedDateTime;
		type Instant = import("@js-joda/core").Instant;
		type Duration = import("@js-joda/core").Duration;
		type LocalDateTime = import("@js-joda/core").LocalDateTime;
		type LocalTime = import("@js-joda/core").LocalTime;
		type LocalDate = import("@js-joda/core").LocalDate;
	}
	namespace rules {
		type RuleCallback = RuleCallback;
		type RuleConfig = RuleConfig;
	}
	type Quantity = Quantity$1;
}
// Manually written type definitions to avoid problems with lazy loading in index.js
export const log: typeof import("./log");
declare const rules$1: typeof import("./rules");
declare const items$1: typeof import("./items/items");
export const things: typeof import("./things");
export const triggers: typeof import("./triggers");
export const actions: typeof import("./actions/actions");
export const utils: typeof import("./utils");
export const osgi: typeof import("./osgi");
export const cache: typeof import("./cache");
declare const time$1: typeof import("./time");
declare const Quantity$1: typeof getQuantity;
export const QuantityClass: typeof Quantity$1;
export const environment: typeof import("./environment");

export {
	Quantity$1 as Quantity,
	items$1 as items,
	rules$1 as rules,
	time$1 as time,
};

export {};
