name: Check for broken links

# https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

on:
  push:
    branches:
    - main

jobs:

  markdown-link-check:

    name: Check for broken links
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
