name: Fetch openHAB Android Client Docs

on:
  # Repository dispatch event, to be triggerd by an openhab-alexa release
  # or manually from the openhab-android repository
  repository_dispatch:
    types: [update-openhab-android-docs-event]
  workflow_dispatch:

jobs:
  call-reusable-fetch-workflow:
    uses: openhab/openhab-docs/.github/workflows/fetch_external_docs_reusable.yml@main
    with:
      base_source_repository: openhab-android
      base_source_ref: ${{ github.event.client_payload.ref }}
      base_folder: addons/uis/apps
      base_file: android.md
      doc_base_file: USAGE.md
      has_images: true
      is_self_contained: false
